# Development environment, customizable configuration
eureka:
  instance:
    # Custom node registration IP
    ip-address: ${SERVICE_HOST:192.168.0.101}

# Log config
logging:
  level:
    io.github.pnoker: DEBUG
    io.github.pnoker.common.sdk: DEBUG
    com.freud.dcom.utgard.cases.*: INFO